"""empty message

Revision ID: d9bce6030b72
Revises: 7ee45060bf37
Create Date: 2021-03-14 07:40:35.295195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bce6030b72'
down_revision = '7ee45060bf37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('urls', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'updated_on')
    op.drop_column('urls', 'created_on')
    # ### end Alembic commands ###
